In [1]:
import numpy as np
import pandas as pd
import os

In [9]:
data = np.load('/home/cleode5a7/Desktop/analyses_friends_annotations/friends_annotations/annotation_results/DeepgazeMr/s1/friends_s01e01b_locmax_pixel_hw.npz', allow_pickle=True)

In [10]:
data.files


['deepgaze_vals']

In [11]:
print(data['deepgaze_vals'])

[array([[  2.02783107, 215.        , 359.        ]])
 array([[  1.97070123, 202.        , 342.        ]])
 array([[  2.2922687 , 265.        , 363.        ],
        [  2.00972473, 182.        , 401.        ]]) ...
 array([[  2.02783107, 215.        , 359.        ]])
 array([[  2.02783107, 215.        , 359.        ]])
 array([[  2.02783107, 215.        , 359.        ]])]


In [13]:
data['deepgaze_vals'][261]

array([[  3.01094333, 116.        , 170.        ],
       [  2.67420309, 112.        , 515.        ]])

In [14]:
df = pd.DataFrame(data['deepgaze_vals'][261])

In [15]:
df

0      1      2
0  3.010943  116.0  170.0
1  2.674203  112.0  515.0

In [21]:


rows = []

for frame_id, arr in enumerate(data['deepgaze_vals']):
    arr = np.squeeze(arr)  # remove extra dims if any
    
    # Handle the case where arr is a 1D array of length 3 (one point)
    if arr.ndim == 1 and arr.shape[0] == 3:
        arr = np.expand_dims(arr, axis=0)  # make it (1, 3)
    
    # Skip if arr is 0D or invalid
    if arr.ndim == 0:
        continue
    
    # Iterate over all saliency points in this frame
    for point in arr:
        score, h, w = point
        rows.append([frame_id, score, int(h), int(w)])

# Create DataFrame
df = pd.DataFrame(rows, columns=['frame', 'score', 'h', 'w'])


In [24]:
df

frame     score    h    w
0          0  2.027831  215  359
1          1  1.970701  202  342
2          2  2.292269  265  363
3          2  2.009725  182  401
4          3  2.804074  267  365
...      ...       ...  ...  ...
42701  26345  2.027831  215  359
42702  26346  2.027831  215  359
42703  26347  2.027831  215  359
42704  26348  2.027831  215  359
42705  26349  2.027831  215  359

[42706 rows x 4 columns]